// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type GamepageDocumentDataSlicesSlice = GameProductsSlice | GameIntroSlice;

/**
 * Content for GamePage documents
 */
interface GamepageDocumentData {
  /**
   * Slice Zone field in *GamePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gamepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<GamepageDocumentDataSlicesSlice> /**
   * Meta Title field in *GamePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: gamepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *GamePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: gamepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *GamePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gamepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * GamePage document from Prismic
 *
 * - **API ID**: `gamepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GamepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GamepageDocumentData>,
    "gamepage",
    Lang
  >;

type HeroDocumentDataSlicesSlice =
  | EventsCalendarSlice
  | BannerSlice
  | GameSelectorSlice;

/**
 * Content for hero documents
 */
interface HeroDocumentData {
  /**
   * Slice Zone field in *hero*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HeroDocumentDataSlicesSlice> /**
   * Meta Title field in *hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hero.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hero.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *hero*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * hero document from Prismic
 *
 * - **API ID**: `hero`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeroDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HeroDocumentData>, "hero", Lang>;

export type AllDocumentTypes = GamepageDocument | HeroDocument;

/**
 * Item in *Banner → Default → Primary → BannerEntry*
 */
export interface BannerSliceDefaultPrimaryBannerentryItem {
  /**
   * BannerInfo field in *Banner → Default → Primary → BannerEntry*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.bannerentry[].bannerinfo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bannerinfo: prismic.RichTextField;

  /**
   * BannerImg field in *Banner → Default → Primary → BannerEntry*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.bannerentry[].bannerimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bannerimg: prismic.ImageField<never>;
}

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * BannerEntry field in *Banner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.bannerentry[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  bannerentry: prismic.GroupField<
    Simplify<BannerSliceDefaultPrimaryBannerentryItem>
  >;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Item in *EventsCalendar → Default → Primary → events*
 */
export interface EventsCalendarSliceDefaultPrimaryEventsItem {
  /**
   * EventDate field in *EventsCalendar → Default → Primary → events*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: events_calendar.default.primary.events[].eventdate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  eventdate: prismic.DateField;

  /**
   * EventTitle field in *EventsCalendar → Default → Primary → events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_calendar.default.primary.events[].eventtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eventtitle: prismic.KeyTextField;

  /**
   * Eventdescription field in *EventsCalendar → Default → Primary → events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_calendar.default.primary.events[].eventdescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eventdescription: prismic.RichTextField;

  /**
   * EventType field in *EventsCalendar → Default → Primary → events*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: events_calendar.default.primary.events[].eventtype
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  eventtype: prismic.SelectField<
    "Torneo" | "Preventa" | "Lanzamiento" | "Evento Especial"
  >;
}

/**
 * Primary content in *EventsCalendar → Default → Primary*
 */
export interface EventsCalendarSliceDefaultPrimary {
  /**
   * Title field in *EventsCalendar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_calendar.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *EventsCalendar → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_calendar.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * events field in *EventsCalendar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: events_calendar.default.primary.events[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  events: prismic.GroupField<
    Simplify<EventsCalendarSliceDefaultPrimaryEventsItem>
  >;
}

/**
 * Default variation for EventsCalendar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsCalendarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventsCalendarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventsCalendar*
 */
type EventsCalendarSliceVariation = EventsCalendarSliceDefault;

/**
 * EventsCalendar Shared Slice
 *
 * - **API ID**: `events_calendar`
 * - **Description**: EventsCalendar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsCalendarSlice = prismic.SharedSlice<
  "events_calendar",
  EventsCalendarSliceVariation
>;

/**
 * Item in *GameIntro → Default → Primary → GameNews*
 */
export interface GameIntroSliceDefaultPrimaryGamenewsItem {
  /**
   * Flipselect field in *GameIntro → Default → Primary → GameNews*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gamenews[].flipselect
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  flipselect: prismic.SelectField<"no" | "yes">;

  /**
   * Foil field in *GameIntro → Default → Primary → GameNews*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gamenews[].foil
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  foil: prismic.SelectField<"no" | "yes">;

  /**
   * CardImg field in *GameIntro → Default → Primary → GameNews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gamenews[].cardimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cardimg: prismic.ImageField<never>;

  /**
   * CardName field in *GameIntro → Default → Primary → GameNews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gamenews[].cardname
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cardname: prismic.KeyTextField;

  /**
   * FlippedImg field in *GameIntro → Default → Primary → GameNews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gamenews[].flippedimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  flippedimg: prismic.ImageField<never>;

  /**
   * FlippedName field in *GameIntro → Default → Primary → GameNews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gamenews[].flippedname
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  flippedname: prismic.KeyTextField;
}

/**
 * Primary content in *GameIntro → Default → Primary*
 */
export interface GameIntroSliceDefaultPrimary {
  /**
   * GameBackground field in *GameIntro → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gamebackground
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gamebackground: prismic.ImageField<never>;

  /**
   * GameTitle field in *GameIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gametitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gametitle: prismic.KeyTextField;

  /**
   * GameDescription field in *GameIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gamedescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  gamedescription: prismic.RichTextField;

  /**
   * Newstitle field in *GameIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.newstitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  newstitle: prismic.KeyTextField;

  /**
   * NewsDescription field in *GameIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.newsdescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  newsdescription: prismic.RichTextField;

  /**
   * GameNews field in *GameIntro → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: game_intro.default.primary.gamenews[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gamenews: prismic.GroupField<
    Simplify<GameIntroSliceDefaultPrimaryGamenewsItem>
  >;
}

/**
 * Default variation for GameIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GameIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GameIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GameIntro*
 */
type GameIntroSliceVariation = GameIntroSliceDefault;

/**
 * GameIntro Shared Slice
 *
 * - **API ID**: `game_intro`
 * - **Description**: GameIntro
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GameIntroSlice = prismic.SharedSlice<
  "game_intro",
  GameIntroSliceVariation
>;

/**
 * Item in *GameProducts → Default → Primary → ProductDisplay*
 */
export interface GameProductsSliceDefaultPrimaryProductdisplayItem {
  /**
   * size field in *GameProducts → Default → Primary → ProductDisplay*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: game_products.default.primary.productdisplay[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"small" | "medium" | "large">;

  /**
   * ProductImg field in *GameProducts → Default → Primary → ProductDisplay*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: game_products.default.primary.productdisplay[].productimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  productimg: prismic.ImageField<never>;

  /**
   * ProductLink field in *GameProducts → Default → Primary → ProductDisplay*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: game_products.default.primary.productdisplay[].productlink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  productlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * description field in *GameProducts → Default → Primary → ProductDisplay*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_products.default.primary.productdisplay[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *GameProducts → Default → Primary*
 */
export interface GameProductsSliceDefaultPrimary {
  /**
   * productTitle field in *GameProducts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_products.default.primary.producttitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  producttitle: prismic.KeyTextField;

  /**
   * ProductDisplay field in *GameProducts → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: game_products.default.primary.productdisplay[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  productdisplay: prismic.GroupField<
    Simplify<GameProductsSliceDefaultPrimaryProductdisplayItem>
  >;
}

/**
 * Default variation for GameProducts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GameProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GameProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GameProducts*
 */
type GameProductsSliceVariation = GameProductsSliceDefault;

/**
 * GameProducts Shared Slice
 *
 * - **API ID**: `game_products`
 * - **Description**: GameProducts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GameProductsSlice = prismic.SharedSlice<
  "game_products",
  GameProductsSliceVariation
>;

/**
 * Item in *GameSelector → Default → Primary → Games*
 */
export interface GameSelectorSliceDefaultPrimaryGamesItem {
  /**
   * CardBack field in *GameSelector → Default → Primary → Games*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: game_selector.default.primary.games[].cardback
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cardback: prismic.ImageField<never>;

  /**
   * GameName field in *GameSelector → Default → Primary → Games*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_selector.default.primary.games[].gamename
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gamename: prismic.KeyTextField;
}

/**
 * Primary content in *GameSelector → Default → Primary*
 */
export interface GameSelectorSliceDefaultPrimary {
  /**
   * title field in *GameSelector → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_selector.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *GameSelector → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game_selector.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Games field in *GameSelector → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: game_selector.default.primary.games[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  games: prismic.GroupField<Simplify<GameSelectorSliceDefaultPrimaryGamesItem>>;
}

/**
 * Default variation for GameSelector Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GameSelectorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GameSelectorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GameSelector*
 */
type GameSelectorSliceVariation = GameSelectorSliceDefault;

/**
 * GameSelector Shared Slice
 *
 * - **API ID**: `game_selector`
 * - **Description**: GameSelector
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GameSelectorSlice = prismic.SharedSlice<
  "game_selector",
  GameSelectorSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GamepageDocument,
      GamepageDocumentData,
      GamepageDocumentDataSlicesSlice,
      HeroDocument,
      HeroDocumentData,
      HeroDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimaryBannerentryItem,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      EventsCalendarSlice,
      EventsCalendarSliceDefaultPrimaryEventsItem,
      EventsCalendarSliceDefaultPrimary,
      EventsCalendarSliceVariation,
      EventsCalendarSliceDefault,
      GameIntroSlice,
      GameIntroSliceDefaultPrimaryGamenewsItem,
      GameIntroSliceDefaultPrimary,
      GameIntroSliceVariation,
      GameIntroSliceDefault,
      GameProductsSlice,
      GameProductsSliceDefaultPrimaryProductdisplayItem,
      GameProductsSliceDefaultPrimary,
      GameProductsSliceVariation,
      GameProductsSliceDefault,
      GameSelectorSlice,
      GameSelectorSliceDefaultPrimaryGamesItem,
      GameSelectorSliceDefaultPrimary,
      GameSelectorSliceVariation,
      GameSelectorSliceDefault,
    };
  }
}
