// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  events_calendar: dynamic(() => import("./EventsCalendar")),
  game_intro: dynamic(() => import("./GameIntro")),
  game_products: dynamic(() => import("./GameProducts")),
  game_selector: dynamic(() => import("./GameSelector")),
};
